import numpy as np
from numpy.typing import ArrayLike, NDArray

def py_bezier_basis(s: float, t: float) -> NDArray[np.float64]: ...
def py_bezier_basis_derivative_wrt_s(s: float, t: float) -> NDArray[np.float64]: ...
def py_bezier_basis_derivative_wrt_t(s: float, t: float) -> NDArray[np.float64]: ...
def py_fourier_mode(phi: float, index: int, periodicity: int = 1) -> float: ...

class FourierBezierConstructor:
    def __init__(self, grid_ggd: object, coefficients: ArrayLike | None = None) -> None: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @coefficients.setter
    def coefficients(self, coefficients: ArrayLike) -> None: ...
    def average_gaussian_faces(self, phi: float) -> NDArray[np.float64]: ...
    def average_gaussian_faces_per_toroidal(self, phis: ArrayLike) -> NDArray[np.float64]: ...
